In [122]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\Komal\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


<h1>NUMPY Problems<h1>


 **1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]**


In [123]:
import numpy as np
original_list= [12.23, 13.32, 100, 36.32]
print("Orignal list before converting: ",original_list)

onedimentional_arr=np.array(original_list)
print("List After converting into one diamentional array: ",onedimentional_arr)

Orignal list before converting:  [12.23, 13.32, 100, 36.32]
List After converting into one diamentional array:  [ 12.23  13.32 100.    36.32]


**2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]**

In [124]:
import numpy as np

matrix=np.arange(2,11).reshape(3,3) 

print("Two Dimentional Array Is: ",matrix)

Two Dimentional Array Is:  [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


__3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]__

In [125]:
import numpy as np

null_arr=np.zeros(10)
print("Null Vector array is with Zero: ",null_arr)

null_arr[6]=11
print("After changed value at 6th Index : ",null_arr)

Null Vector array is with Zero:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After changed value at 6th Index :  [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


**4.Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]**

In [126]:
import numpy as np

arr=np.arange(12,38)
print("Original array is: ",arr)
print("Reverse array is:")
print(arr[::-1])

Original array is:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array is:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


**5. Write a Python program to create a 2d array with 1 on the border and 0 inside. Expected Output: Original array: [[ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.]]1 on the border and 0 inside in the array [[ 1. 1. 1. 1. 1.] [ 1. 0. 0. 0. 1.] [ 1. 0. 0. 0. 1.] [ 1. 0. 0. 0. 1.] [ 1. 1. 1. 1. 1.]]**

In [127]:
import numpy as np
two_d_array = np.ones((5,5))
print("Original array:")
print(two_d_array)
print("1 on the border and 0 inside in the array")
two_d_array[1:-1,1:-1] = 0
#two_d_array[1:4,1:4]=0
print(two_d_array)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]**

In [128]:
import numpy as np
arr = np.ones((3, 3))
  
print("Original array",arr)
print("0 on the border and 1 inside the array")
arr = np.pad(arr, pad_width=1, mode='constant',
               constant_values=0)
print(arr)

Original array [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]**


In [129]:
import numpy as np


arr=np.zeros((8,8))
print("Orignal Array Is: ")
print(arr)
arr[1::2,::2]=1
arr[::2,1::2]=1
print("Checkoboard Pattern is: ")
print(arr)


Orignal Array Is: 
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Checkoboard Pattern is: 
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]**

In [130]:
import numpy as np

list = [1, 2, 3, 4, 5, 6, 7, 8]
list=np.asarray(list)
print("List to array: ",list)

tup= ([8, 4, 6] ,[1, 2, 3])
tup=np.asarray(tup)
print("Tuple to array is : ",tup)


List to array:  [1 2 3 4 5 6 7 8]
Tuple to array is :  [[8 4 6]
 [1 2 3]]


**9. Write a Python program to append values to the end of an array. Expected Output: Original array: [10, 20, 30] After append values to the end of the array: [10 20 30 40 50 60 70 80 90]**

In [131]:
import numpy as np

arr = [10,20,30]
print("This Is original  Array: ",arr)
finalarr = np.append(arr,[40,50,60,70,80,90],axis=0)
print("Added Values at end in orginal Array : ",finalarr)

This Is original  Array:  [10, 20, 30]
Added Values at end in orginal Array :  [10 20 30 40 50 60 70 80 90]


**10. Write a Python program to find the real and imaginary parts of an array of complex numbers. Expected Output: Original array [ 1.00000000+0.j 0.70710678+0.70710678j] Real part of the array: [ 1. 0.70710678] Imaginary part of the array: [ 0. 0.70710678]**

In [132]:
import numpy as np

arr1 = np.sqrt([1.0000+0j])
arr2 = np.sqrt([0+1j])

print("Original array: arr1 : ",arr1)
print("Original array: arr2 : ",arr2 )

print("Real part of the array is: ")
print(arr1.real)
print(arr2.real )

print("Imaginary part of the array is: ")
print(arr1.imag)
print(arr2.imag)

Original array: arr1 :  [1.+0.j]
Original array: arr2 :  [0.707+0.707j]
Real part of the array is: 
[1.]
[0.707]
Imaginary part of the array is: 
[0.]
[0.707]


**11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24**

In [133]:
import numpy as np
arr = np.array([1,2,3], dtype=np.float64)

print("Array is: ",arr )
print("Size of an array is: ", arr.size)
print("Length of one element of an array in bytes is: ", arr.itemsize)
print("Total bytes consumed by the elements of the array is: ", arr.nbytes)

Array is:  [1. 2. 3.]
Size of an array is:  3
Length of one element of an array in bytes is:  8
Total bytes consumed by the elements of the array is:  24


**12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]**

In [134]:
import numpy as np

arr1 = np.array([0,10,20,40,60])
arr2 = np.array([10,30,40])

print("First Array is: ",arr1)
print("Second Array is: ",arr2)

print("Common Values Between First array And Second array is: ", np.intersect1d(arr1,arr2))

First Array is:  [ 0 10 20 40 60]
Second Array is:  [10 30 40]
Common Values Between First array And Second array is:  [10 40]


**13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]**

In [135]:
import numpy as np

arr1 = np.array([0,10,20,40,60,80])
arr2 = np.array([10,30,40,50,70,90])

print("First Array is: ",arr1)
print("Second Array is: ",arr2)

print("Unique values in first array that are not in second array: ", np.setdiff1d(arr1,arr2))


First Array is:  [ 0 10 20 40 60 80]
Second Array is:  [10 30 40 50 70 90]
Unique values in first array that are not in second array:  [ 0 20 60 80]


**14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]**

In [136]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)

array2 = np.array([10, 30, 40, 50, 70])
print("Array2: ",array2)

print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


**15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]**

In [137]:
import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])

print("Array a: ",a)
print("Array b: ",b)

print("a > b: ")
print(np.greater(a, b))

print("a >= b: ")
print(np.greater_equal(a, b))

print("a < b: ")
print(np.less(a, b))

print("a <= b: ")
print(np.less_equal(a, b))


Array a:  [1 2]
Array b:  [4 5]
a > b: 
[False False]
a >= b: 
[False False]
a < b: 
[ True  True]
a <= b: 
[ True  True]


**16. Write a Python program to save a NumPy array to a text file.**

In [138]:
import numpy as np 

# Creating an array
List = [1, 2, 3, 4, 5]
Array = np.array(List)

# Displaying the array
print('Array:\n', Array)
file = open("filechecknumpy.txt", "w+")

# Saving the array in a filechecknumpy.txt file
content = str(Array)
file.write(content)
file.close()

# Displaying the contents of the filechecknumpy.txt file
file = open("filechecknumpy.txt", "r")
content = file.read()

print("\nContent in filechecknumpy.txt:\n", content)
file.close()

Array:
 [1 2 3 4 5]

Content in filechecknumpy.txt:
 [1 2 3 4 5]


**17. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]**

In [139]:
import numpy as np
arr = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:",arr)
arr1 = np.ravel(arr)
print("New flattened array:")
print(arr1)

Original array: [[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


**18. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]**

In [140]:
import numpy as np

arr1 = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(arr1)
print("Data type of the array  is:",arr1.dtype)
# Change the data type of arr1
arr2 = arr1.astype(float)
print("New Type: ",arr2.dtype)
print(arr2)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array  is: int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


**19.Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]**

In [141]:
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**20.Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]**

In [142]:
import numpy as np
arr = np.tri(4, 3, -1)
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


**21. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]**

In [143]:
import numpy as np
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])
arr3 = np.concatenate((arr1, arr2), 1)
print(arr3)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


**22.Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only**

In [144]:
import numpy as np
arr = np.zeros(5)
print(arr)
arr.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
arr[0] = 1

[0. 0. 0. 0. 0.]
Test the array is read-only or not:
Try to change the value of the first element:


ValueError: assignment destination is read-only

**23. Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array. Expected Output: Original array elements: [[ 0 1 2 3] [ 4 5 6 7] [ 8 9 10 11]] New array elements: [[ 0 3 6 9] [12 15 18 21] [24 27 30 33]]**

In [ ]:
import numpy as np

arr= np.arange(12).reshape(3, 4)
print("Original array elements:")
print(arr)

for a in np.nditer(arr, op_flags=['readwrite']):
    a[...] = 3 * a
    
print("New array elements:")
print(arr)


Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


**24. Write a Python program to convert a NumPy array into Python list structure. Expected Output: Original array elements: [[0 1] [2 3] [4 5]] Array to list: [[0, 1], [2, 3], [4, 5]]**

In [ ]:
import numpy as np

arr= np.arange(6).reshape(3, 2)

print("Original array elements:")
print(arr)

print("Array to list:")
print(arr.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


**25. Write a Python program to convert a NumPy array into Python list structure. Expected Output:Original array elements: [ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349 0.35399976 0.99469633 0.0694458 0.54711478] Print array values with precision 3: [ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]**

In [ ]:
import numpy as np

arr=np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,             
  0.35399976, 0.99469633, 0.0694458, 0.54711478]) 

print("Original array elements:",arr)
print("Print array values with precision 3:")
np.set_printoptions(precision=3)
print(arr)

Original array elements: [0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]
Print array values with precision 3:
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


**26. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]**

In [ ]:
import numpy as np
arr=np.array([1.6e-10, 1.6, 1200, .235]) 
print("Original array elements:",arr)
print("Print array values with precision 3:")
np.set_printoptions(suppress=True)
print(arr)

Original array elements: [1.60e-10 1.60e+00 1.20e+03 2.35e-01]
Print array values with precision 3:
[   0.       1.6   1200.       0.235]


**27. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]**

In [ ]:
import numpy as np

array1 = np.array([[10,20,30], [40,50,60]])
array2= np.array([[100], [200]])
print(np.append(array1, array2, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


**28. Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]**

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
index = [0, 3, 4]
print("Original array:")
print(arr)
print("Delete first, fourth and fifth elements:")

new_arr = np.delete(arr, index)
print(new_arr)

Original array:
[ 10  20  30  40  50  60  70  80  90 100]
Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]
